POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "author": "Aleksi Salin",
    "title": "How to make a baby with your step mom - a walkthrough",
    "url": "http://tpkanslia.com/nato-blog"
}